---
title: "DeltaOutflowPlotting"
author: "Caroline Newell"
date: "2/23/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
library(readr)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(lfstat)
```

```{r}
DeltaFlow_WaterYears1960_2021 <- read_csv("1960 to present/data/DeltaFlow_WaterYears1960_2021.csv")

drought_years<-c(1976, 1977, 1987, 1988, 1989, 1990, 1991, 1992, 2007, 2008, 2009, 2012, 2013, 2014, 2015, 2016, 2020, 2021) #data from: https://water.ca.gov/water-basics/drought  and Peter (2020, 2021)

```

# Now we plot
```{r}
#basic bubble plots
ggplot(DeltaFlow_WaterYears1960_2021, aes(x=Date, y=TOT)) +
  geom_line() +
  xlab("")+
  ylab("Inflow")

ggplot(DeltaFlow_WaterYears1960_2021, aes(x=Date, y=EXPORTS)) +
  geom_line() +
  xlab("")+
  ylab("Exports")

ggplot(DeltaFlow_WaterYears1960_2021, aes(x=Date)) +
  geom_line(aes(y=TOT), color = "steelblue") +
  geom_line(aes(y=EXPORTS), color = "darkred", linetype = "twodash") +
  xlab("Water Year") +
  theme(legend.position = c(.95, .95),
        legend.justification = c("right", "top"),
        legend.box.just = "right",
        legend.margin = margin(6, 6, 6, 6))

#Wont make a legend :( Gotta collapse the two variables into key-value pairs and then visualize

df<- DeltaFlow_WaterYears1960_2021 %>% 
  select(Date, TOT, EXPORTS) %>% 
  gather(key="variable", value = "value", -Date)
head(df)

ggplot(df, aes(x=Date, y=value))+
  geom_line(aes(color = variable)) +
  scale_color_manual(values = c("darkred", "steelblue"))+
  facet_wrap(~variable, scales = "free")
```

John's response: You are close! There is so much noise that it makes it hard to read a signal. Try summing up by years, then create a stacked plot on one axis in MAF and see if we can get some traction.

```{r}
ggplot(DeltaFlow_WaterYears1960_2021, aes(x=WaterYear))+
  geom_bar(aes(y=TOT_MAF), stat="identity", color="black", fill="steelblue")+
  geom_line(aes(y=Exports_MAF, group =1), color="red", size=1.1) +
  xlab("Water Year") + ylab("MAF")

str(DeltaFlow_WaterYears1960_2021)
#Export trend line:
ggplot(DeltaFlow_WaterYears1960_2021, aes(x=WaterYear)) +geom_rect(aes(xmin=1976, xmax=1977, ymin=0, ymax=Inf), fill = "grey75", alpha = .1) +
  geom_rect(aes(xmin=1987, xmax=1992, ymin=0, ymax=Inf),fill = "grey75", alpha = .1) +
  geom_rect(aes(xmin=2007, xmax=2009, ymin=0, ymax=Inf),fill = "grey75", alpha = .1) +
  geom_rect(aes(xmin=2012, xmax=2016, ymin=0, ymax=Inf),fill = "grey75", alpha = .1)+
  geom_bar(aes(y=TOT_MAF), stat="identity", color="black", fill="steelblue") + 
  geom_line(aes(y=Exports_MAF, group =1), color="red", size=1.1) + xlab("Water Year") +  ylab("MAF") + ggtitle("Total Delta Inflow and Exports")+ scale_x_continuous(breaks=c(1960, 1970, 1980, 1990, 2000, 2010, 2020))+
  theme_classic(base_size=16) 

#Export bars: 
ggplot(DeltaFlow_WaterYears1960_2021, aes(x=WaterYear)) +geom_rect(aes(xmin=1976, xmax=1977, ymin=0, ymax=Inf), fill = "grey75", alpha = .1) +
  geom_rect(aes(xmin=1987, xmax=1992, ymin=0, ymax=Inf),fill = "grey75", alpha = .1) +
  geom_rect(aes(xmin=2007, xmax=2009, ymin=0, ymax=Inf),fill = "grey75", alpha = .1) +
  geom_rect(aes(xmin=2012, xmax=2016, ymin=0, ymax=Inf),fill = "grey75", alpha = .1)+
  geom_rect(aes(xmin=2020, xmax=2021, ymin=0, ymax=Inf),fill = "grey75", alpha = .1)+
  geom_bar(aes(y=TOT_MAF), stat="identity", color="black", fill="steelblue") + 
  geom_bar(aes(y=Exports_MAF), stat="identity", color="black", fill="red") + xlab("Water Year") +  ylab("MAF") + ggtitle("Total Delta Inflow and Exports")+ scale_x_continuous(breaks=c(1960, 1970, 1980, 1990, 2000, 2010, 2020))+
  theme_classic(base_size=16) 
```

# Delta Outflow for Marginata - 1980 to present
```{r}
DeltaOutflow_WaterYears1960_2021 <- read_csv("1960 to present/data/DeltaOutflow_WaterYears1960_2021.csv")

#Outflow bars: 
DeltaOutflow_WaterYears1960_2021 %>% filter(WaterYear > 1980) %>% 
  ggplot(aes(x=WaterYear)) +
  geom_rect(aes(xmin=1987, xmax=1992, ymin=0, ymax=Inf),fill = "grey75", alpha = .1) +
  geom_rect(aes(xmin=2007, xmax=2009, ymin=0, ymax=Inf),fill = "grey75", alpha = .1) +
  geom_rect(aes(xmin=2012, xmax=2016, ymin=0, ymax=Inf),fill = "grey75", alpha = .1)+
  geom_rect(aes(xmin=2020, xmax=2021, ymin=0, ymax=Inf),fill = "grey75", alpha = .1)+
  geom_bar(aes(y=Outflow_MAF), stat="identity", color="black", fill="steelblue") + 
  xlab("Water Year") +  ylab("MAF") + ggtitle("Total Delta Outflow")+ scale_x_continuous(breaks=c(1980, 1990, 2000, 2010, 2020))+
  theme_classic(base_size=16) 

#Outflow line
DeltaOutflow_WaterYears1960_2021 %>% filter(WaterYear > 1980) %>% 
  ggplot(aes(x=WaterYear)) +
  geom_rect(aes(xmin=1987, xmax=1992, ymin=0, ymax=Inf),fill = "grey75", alpha = .1) +
  geom_rect(aes(xmin=2007, xmax=2009, ymin=0, ymax=Inf),fill = "grey75", alpha = .1) +
  geom_rect(aes(xmin=2012, xmax=2016, ymin=0, ymax=Inf),fill = "grey75", alpha = .1)+
  geom_rect(aes(xmin=2020, xmax=2021, ymin=0, ymax=Inf),fill = "grey75", alpha = .1)+
  geom_area(aes(y=Outflow_MAF), color="black", fill="steelblue") + 
  xlab("Water Year") +  ylab("MAF") + ggtitle("Total Delta Outflow")+ scale_x_continuous(breaks=c(1980, 1990, 2000, 2010, 2020))+
  theme_classic(base_size=16) 

```